// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aqliyaglegptltfayjuh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxbGl5YWdsZWdwdGx0ZmF5anVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0Njg2MTQsImV4cCI6MjA2OTA0NDYxNH0.PPX7qrtv54Y59JPH9FNGNDcCJh4ICg97wgA7IfjjCtU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});