// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rhnpeawxqbvlcihrxjmq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJobnBlYXd4cWJ2bGNpaHJ4am1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzODE3OTUsImV4cCI6MjA2ODk1Nzc5NX0.XfG9lOnD_hAVDv7McKLwMaDgeNf-NwUemycGRATPqsE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});